Fix single qubit deallocation entanglement check (#1380)
The following example fails with an unexpected error.
```python
@qml.qjit(capture=True)
@qml.transforms.ppr_to_ppm
@qml.transforms.to_ppr
@qml.qnode(qml.device("lightning.qubit", wires=2))
def circuit():
    qml.H(0)
    qml.CNOT([0, 1])
    return qml.probs()

print(circuit())

>>> RuntimeError: [/Users/isaac/Documents/pennylane-lightning/pennylane_lightning/core/simulators/lightning_qubit/catalyst/LightningSimulator.cpp:64][Function:AllocateQubit] Error in Catalyst Runtime: Cannot reuse qubit: qubit is entangled with remaining qubits. Release qubits must be disentangled.
```

This PR addresses the issue. The underlying cause is due to a
mishandling of the qubit representation in the purity calculation of the
density matrix during the single qubit allocation.

[[sc-111805]]


Relevant PR: 
https://github.com/PennyLaneAI/catalyst/pull/2348 
https://github.com/PennyLaneAI/pennylane-lightning/pull/1321

---------

Co-authored-by: Jake Zaia <23638795+jzaia18@users.noreply.github.com>